# Generated by Django 5.2.13 on 2026-04-10 23:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionYOLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('confidence_threshold', models.FloatField(default=0.5, help_text='Umbral de confianza (0.0 a 1.0)')),
                ('iou_threshold', models.FloatField(default=0.45, help_text='Threshold para NMS (Non-Maximum Suppression)')),
                ('input_size', models.IntegerField(default=640, help_text='Tamaño de entrada del modelo (ej: 416, 640, 1280)')),
                ('clases_permitidas', models.JSONField(default=list, help_text='Lista de IDs de clases a detectar. Vacío = todas.')),
                ('es_default', models.BooleanField(default=False)),
                ('esta_activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración YOLO',
                'verbose_name_plural': 'Configuraciones YOLO',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPERVISOR', 'Supervisor')], default='SUPERVISOR', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CacheResultadoYOLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(help_text='Hash único basado en imagen + configuración', max_length=128, unique=True)),
                ('placa_detectada', models.CharField(max_length=20)),
                ('confianza', models.FloatField()),
                ('hit_count', models.IntegerField(default=1)),
                ('primera_vez', models.DateTimeField(auto_now_add=True)),
                ('ultima_vez', models.DateTimeField(auto_now=True)),
                ('expira_en', models.DateTimeField(help_text='Cuándo expira este cache')),
            ],
            options={
                'verbose_name': 'Cache Resultado YOLO',
                'verbose_name_plural': 'Cache Resultados YOLO',
                'ordering': ['-hit_count', '-ultima_vez'],
                'indexes': [models.Index(fields=['cache_key'], name='api_cachere_cache_k_0aa2f2_idx'), models.Index(fields=['placa_detectada'], name='api_cachere_placa_d_cffa6b_idx'), models.Index(fields=['expira_en'], name='api_cachere_expira__03c7b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricaRendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LATENCIA_INFERENCIA', 'Latencia de inferencia'), ('LATENCIA_TOTAL', 'Latencia total (captura a respuesta)'), ('DETECCION_OK', 'Detección exitosa'), ('DETECCION_ERROR', 'Error en detección'), ('OCR_ACERTADO', 'OCR acertado'), ('OCR_FALLIDO', 'OCR fallido')], max_length=30)),
                ('valor', models.FloatField(help_text='Valor de la métrica (ms para latencias)')),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Métrica de Rendimiento',
                'verbose_name_plural': 'Métricas de Rendimiento',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tipo', '-timestamp'], name='api_metrica_tipo_967d84_idx'), models.Index(fields=['placa', '-timestamp'], name='api_metrica_placa_cc27c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('permisos', models.JSONField(default=dict, help_text="Diccionario de permisos: {'lectura': True, 'escritura': False, ...}")),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
    ]
