# Generated by Django 5.2.13 on 2026-04-20 06:13

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', api.models.UsuarioManager()),
            ],
        ),
    ]
