# Generated by Django 5.2.12 on 2026-04-05 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_accesslog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessLog',
        ),
    ]
