server {
    listen 80;
    server_name 10.104.99.123;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name 10.104.99.123;

    ssl_certificate /etc/nginx/certs/scavi.crt;
    ssl_certificate_key /etc/nginx/certs/scavi.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    # Security headers (OWASP)
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Rutas para el Frontend
    location / {
        proxy_pass http://web:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # WebSocket support for Django Channels
    location /ws/ {
        proxy_pass http://api:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Rutas para el Backend / API
    location /api/ {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Admin de Django:
    location /admin/ {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
    }

    # Archivos estáticos de Django (Django los debe recopilar aquí)
    location /static/ {
        alias /app/staticfiles/;
    }
}
