server {
    listen 80;

    # Rutas para el Frontend
    location / {
        proxy_pass http://web:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Rutas para el Backend / API
    location /api/ {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Admin de Django:
    location /admin/ {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
    }

    # Archivos estáticos de Django (Django los debe recopilar aquí)
    location /static/ {
        alias /app/static/;
    }
}