# Generated by Django 5.2.12 on 2026-04-05 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_maxima', models.IntegerField()),
                ('plano_svg_url', models.URLField(blank=True, help_text='Ruta al archivo SVG base', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('identificador_svg', models.CharField(help_text='ID del elemento en el SVG de React', max_length=100, unique=True)),
                ('url_stream', models.CharField(help_text='URL HLS, DASH o WebRTC', max_length=255)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('MANTENIMIENTO', 'En Mantenimiento')], default='ACTIVA', max_length=20)),
                ('parqueo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camaras', to='infraestructura.parqueo')),
            ],
        ),
    ]
