# Generated by Django 5.2.12 on 2026-04-05 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infraestructura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('DOCENTE', 'Docente'), ('ESTUDIANTE', 'Estudiante'), ('VISITANTE', 'Visitante'), ('ADMINISTRATIVO', 'Administrativo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado_acceso', models.CharField(choices=[('AUTORIZADO', 'Autorizado'), ('DENEGADO', 'Denegado'), ('DESCONOCIDO', 'Desconocido')], default='DENEGADO', max_length=20)),
                ('camara', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infraestructura.camara')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trafico.vehiculo')),
            ],
        ),
    ]
