# Generated by Django 5.2.13 on 2026-04-10 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaProcesamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='cola_procesamiento/')),
                ('device_id', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20)),
                ('resultado_json', models.JSONField(blank=True, null=True)),
                ('error_mensaje', models.TextField(blank=True)),
                ('prioridad', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cola de Procesamiento',
                'verbose_name_plural': 'Cola de Procesamiento',
                'ordering': ['prioridad', '-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='confianza_ia',
            field=models.FloatField(blank=True, help_text='Porcentaje de certeza de YOLOv8 (0.0 a 1.0)', null=True),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='imagen_evidencia',
            field=models.ImageField(blank=True, help_text='Recorte de la placa en el momento exacto', null=True, upload_to='evidencia_placas/'),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='placa_detectada_ia',
            field=models.CharField(blank=True, default='', help_text='Texto extraído de la cámara por YOLO', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='estado_acceso',
            field=models.CharField(choices=[('AUTORIZADO', 'Autorizado'), ('DENEGADO', 'Denegado'), ('DESCONOCIDO', 'Vehículo No Registrado')], default='DENEGADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trafico.vehiculo'),
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACCESOS_DIARIOS', 'Accesos por día'), ('VEHICULOS_UNICOS', 'Vehículos únicos'), ('DETECCIONES_POR_HORA', 'Detecciones por hora'), ('TASA_AUTORIZACION', 'Tasa de autorización'), ('RENDIMIENTO_PROMEDIO', 'Rendimiento promedio')], max_length=30)),
                ('valor', models.FloatField()),
                ('fecha', models.DateField()),
                ('metadata', models.JSONField(default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estadística',
                'verbose_name_plural': 'Estadísticas',
                'indexes': [models.Index(fields=['tipo', 'fecha'], name='trafico_est_tipo_0ab98c_idx')],
                'unique_together': {('tipo', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ERROR_INFERENCIA', 'Error de inferencia YOLO'), ('BAJA_CONFIANZA', 'Baja confianza de detección'), ('ACCESO_SOSPECHOSO', 'Acceso sospechoso'), ('FALLA_CAMARA', 'Falla de cámara'), ('SISTEMA', 'Alerta del sistema')], max_length=30)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('esta_resuelta', models.BooleanField(default=False)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='trafico.registroacceso')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['tipo', '-creado_en'], name='trafico_ale_tipo_426a28_idx'), models.Index(fields=['esta_resuelta', '-creado_en'], name='trafico_ale_esta_re_e459ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogDeteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('DETECCION_PLACA', 'Detección de placa'), ('OCR_TEXTO', 'OCR de texto'), ('Coincidencia_DB', 'Coincidencia en base de datos'), ('ACCESO_AUTORIZADO', 'Acceso autorizado'), ('ACCESO_DENEGADO', 'Acceso denegado')], max_length=30)),
                ('mensaje', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('registro_acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_deteccion', to='trafico.registroacceso')),
            ],
            options={
                'verbose_name': 'Log de Detección',
                'verbose_name_plural': 'Logs de Detección',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tipo_evento', '-timestamp'], name='trafico_log_tipo_ev_a1cd9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('es_autorizado', models.BooleanField(default=False, help_text='Indica si este tipo tiene acceso autorizado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='trafico.vehiculo')),
            ],
            options={
                'verbose_name': 'Tipo de Vehículo',
                'verbose_name_plural': 'Tipos de Vehículos',
                'unique_together': {('vehiculo', 'nombre')},
            },
        ),
    ]
