# Generated by Django 5.2.13 on 2026-04-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlateDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='anpr/%Y/%m/%d/')),
                ('placa_texto', models.CharField(blank=True, max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('device_id', models.CharField(blank=True, help_text='ID del dispositivo que generó la detección', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Detección de Placa',
                'verbose_name_plural': 'Detecciones de Placas',
                'ordering': ['-created_at'],
            },
        ),
    ]
